stages:
  - backend test
  - frontend test
  - build backend
  - build frontend    

backend test project:
  stage: backend test
  image: python:3.11.0
  script:  
    - pip install pipenv
    - pip3 install shell
    - pipenv install django
    - pip install django djangorestframework
    - cd brewdog_project/
    - python manage.py migrate
    - python manage.py test

frontend test project:
  stage: frontend test
  image: node:16
  script:
    - cd brewdog_project/frontend/
    - npm install
    - npm i react-scripts
    - npm test

build backend project:
  stage: build backend
  image: python:3.11.0
  script:
    - cd brewdog_project/
    - python manage.py runserver

build frontend project:
  stage: build frontend
  image: node:16
  script:
    - cd brewdog_project/frontend/
    - npm run build 

