stages:
  - Build  
  - Test

Backend Build:
  stage: Build
  image: python:3.11.0
  script:
    - pip install pipenv
    - pip3 install shell
    - pipenv install django
    - pip install django djangorestframework
    - pip install -r requirements.txt
    - cd brewdog_project/
    - python manage.py makemigrations brewdog_api
    - python manage.py makemigrations
    - python manage.py migrate brewdog_api
    - python manage.py migrate

Frontend Build:
  stage: Build
  image: node:16
  script:
    - cd brewdog_project/frontend/
    - npm install
    - npm i react-scripts
    - npm install -D webpack-cli
    - npm run build

Backend Test:
  stage: Test
  image: python:3.11.0
  script:  
    - pip install pipenv
    - pip3 install shell
    - pipenv install django
    - pip install django djangorestframework
    - pip install -r requirements.txt
    - cd brewdog_project/
    - python manage.py makemigrations brewdog_api
    - python manage.py makemigrations
    - python manage.py migrate brewdog_api
    - python manage.py migrate
    - python manage.py test brewdog_api
    - python manage.py test

Frontend Test:
  stage: Test
  image: node:16
  script:
    - cd brewdog_project/frontend/
    - npm install
    - npm i react-scripts
    - npm test
